name: Aseprite Plugin Workflow

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps: 
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Create aseprite-extension file
      run: |
        zip                                           \
          --recurse-paths                             \
          ./dungeondraft-effect.aseprite-extension    \
          README.md                                   \
          LICENSE                                     \
          package.json                                \
          dungeondraft_effect.lua

    - name: Update Release With Files
        id: create_version_release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          name: ${{ github.event.release.name }}
          draft: ${{ github.event.release.unpublished }}
          prerelease: ${{ github.event.release.prerelease }}
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: './dungeondraft-effect.aseprite-extension'
          tag: ${{ github.event.release.tag_name }}
          body: ${{ github.event.release.body }}